// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAUtUsa4NQUUgLYqb9gbE21116kT4snUA',
    appId: '1:896614751960:web:f4cd068da7e1f6550941ad',
    messagingSenderId: '896614751960',
    projectId: 'blockzen-carbon-registry',
    authDomain: 'blockzen-carbon-registry.firebaseapp.com',
    storageBucket: 'blockzen-carbon-registry.firebasestorage.app',
    measurementId: 'G-5L6YD5EDGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTezUJa2yeUTQ9dPA7vYyHCXlH1MlQIes',
    appId: '1:896614751960:android:533c5c843340a6b90941ad',
    messagingSenderId: '896614751960',
    projectId: 'blockzen-carbon-registry',
    storageBucket: 'blockzen-carbon-registry.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPESDRl-q2ZBmg6br-mQbVUBLN9c7jtbs',
    appId: '1:896614751960:ios:6a155cbe8f78936d0941ad',
    messagingSenderId: '896614751960',
    projectId: 'blockzen-carbon-registry',
    storageBucket: 'blockzen-carbon-registry.firebasestorage.app',
    iosBundleId: 'com.example.front',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPESDRl-q2ZBmg6br-mQbVUBLN9c7jtbs',
    appId: '1:896614751960:ios:6a155cbe8f78936d0941ad',
    messagingSenderId: '896614751960',
    projectId: 'blockzen-carbon-registry',
    storageBucket: 'blockzen-carbon-registry.firebasestorage.app',
    iosBundleId: 'com.example.front',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAUtUsa4NQUUgLYqb9gbE21116kT4snUA',
    appId: '1:896614751960:web:a6414e9a1b075c6a0941ad',
    messagingSenderId: '896614751960',
    projectId: 'blockzen-carbon-registry',
    authDomain: 'blockzen-carbon-registry.firebaseapp.com',
    storageBucket: 'blockzen-carbon-registry.firebasestorage.app',
    measurementId: 'G-MXQFC8YZX6',
  );
}
